#This will create this metric in all the tiers, under this path
#metricPrefix: "Custom Metrics|MySQL|"

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Server|Component:<TIER ID>|Custom Metrics|MySQL|"

mySQL:
    - name: "Local MySQL"
      host: "localhost"
      port: 3306
      user: ""
      #Provide password or passwordEncrypted and encryptionKey
      password: ""

      encryptedPassword: ""

      #Slave machines
      #slave:
      #   - name: "Local Slave"
      #     host: "localhost"
      #     port: 3388
      #     user: ""
           #Provide password or passwordEncrypted and encryptionKey
      #     password: ""

           #encryptedPassword: ""


# number of concurrent tasks
numberOfThreads: 5


# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
# Values provided here can be overridden if the same field is configured in either controller-info.xml or system properties.
controllerInfo:
  controllerHost: "localhost"  # -Dappdynamics.controller.hostName
  controllerPort: 8090 # -Dappdynamics.controller.port
  controllerSslEnabled: false # -Dappdynamics.controller.ssl.enabled
  enableOrchestration: false # N/A
  uniqueHostId: "" # -Dappdynamics.agent.uniqueHostId
  username: "" # -Dappdynamics.agent.monitors.controller.username
  password: "" # -Dappdynamics.agent.monitors.controller.password
  encryptedPassword: "" # -Dappdynamics.agent.monitors.controller.encryptedPassword
  accountAccessKey: "" # -Dappdynamics.agent.accountAccessKey
  account: "" # -Dappdynamics.agent.accountName
  machinePath: "" # -Dappdynamics.machine.agent.hierarchyPath
  simEnabled: false # -Dappdynamics.sim.enabled
  applicationName: "" # -Dappdynamics.agent.applicationName
  tierName: "" # -Dappdynamics.agent.tierName
  nodeName: "" # -Dappdynamics.agent.nodeName

encryptionKey: "abcd"

enableHealthChecks: false