mySQL:
    - name: "Local MySQL"
      host: "localhost"
      port: 3388
      user: "root"
      #Provide password or passwordEncrypted and encryptionKey
      password: "root"

      passwordEncrypted:
      encryptionKey:

      #Slave machines
      slave:
         - name: "Local Slave"
           host: "localhost"
           port: 3388
           user: "root"
           #Provide password or passwordEncrypted and encryptionKey
           password:

           passwordEncrypted: "IGVtC9eudmgG8RDjmRjGPQ=="
           encryptionKey: "welcome"


#timeout for the metric collector thread
threadTimeout: 30

# number of concurrent tasks
numberOfThreads: 5


#This will create this metric in all the tiers, under this path
metricPrefix: "Custom Metrics|MySQL|"

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|MySQL|"